name: Manual Trigger Workflow

# Triggers the workflow manually
on:
  workflow_dispatch:

jobs:
  run-scripts:
    runs-on: Linux

    steps:
    # Run existing Python script
    - name: Run Python script
      run: |
        python3 /home/azureuser/script.py "hello, yashpal"
